# Generated by Django 4.2.8 on 2024-12-24 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_follow_user_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', through='accounts.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
